name: deploy
on:
  push:
    branches:
      - master
jobs:
  deploy-cdk-stack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          # Install micromamba.
          wget -qO- https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
          ./bin/micromamba shell hook > ~/.bashrc

          # Install Poetry.
          curl -sSL https://install.python-poetry.org | python3 -

          # Create Mamba environment.
          source ~/.bashrc
          micromamba create --file environment.yml --yes
          micromamba activate aws

          # Install Node.js package dependencies.
          npm ci

          # Install Python package dependencies.
          poetry install

          # Unlock git-crypt.
          echo $GIT_CRYPT_KEY | base64 -d | git-crypt unlock -

          # Deploy CDK stack.
          AWS_CONFIG_FILE=.aws/config npx cdk deploy --require-approval never

          # Assume CDK deploy role for bootstrapping.
          export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s" \
              $(AWS_CONFIG_FILE=.aws/config aws sts assume-role \
                --role-arn arn:aws:iam::961672313229:role/cdk-hnb659fds-deploy-role-961672313229-ap-southeast-2 \
                --role-session-name github-eidorb-aws \
                --query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" \
                --output text))

          # Bootstrap to trust additional principals with CDK deployment.
          AWS_CONFIG_FILE=.aws/config npx cdk bootstrap \
            --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess \
            --trust arn:aws:iam::961672313229:user/Identity-githubeidorbaws9CA4BAE6-SCD6J9HZ03LQ
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
