name: deploy
on:
  push:
    branches:
      - master
jobs:
  deploy-cdk-stack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          # Install micromamba.
          wget -qO- https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
          ./bin/micromamba shell hook > ~/.bashrc

          # Install Poetry.
          curl -sSL https://install.python-poetry.org | python3 -

          # Create Mamba environment.
          source ~/.bashrc
          micromamba create --file environment.yml --yes
          micromamba activate aws

          # Install Node.js package dependencies.
          npm ci

          # Install Python package dependencies.
          poetry install

          # Unlock git-crypt.
          echo $GIT_CRYPT_KEY | base64 -d | git-crypt unlock -

          # Deploy CDK stack.
          AWS_CONFIG_FILE=.aws/config npx cdk deploy --require-approval never
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
